name: takeoff_cli
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.3.1 
  takeoff_lib:
    path: '../takeoff_lib'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0