:toc: macro
toc::[]
:idprefix:
:idseparator: -

= Setting up a Maven library package pipeline using Azure DevOps

In this section you will create a library package pipeline for a maven repo in azure devops.

== Prerequisites

* Library source code repo

== Create maven deploy pipeline

Follow the steps from the link:setup-quality-pipeline.asciidoc[Setup build pipeline section] to create the pipeline. Use the config file located at `scripts/pipelines/azure-devops/templates/library-deploy/deploy-config.cfg`

=== Example

```
./pipeline_generator.sh -c templates/library-deploy/deploy-config.cfg -l quarkus -d C:/projects/libraryrepo -n pipeline-name
```

== Connect library to feed

Follow the link:https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/pom-and-settings?view=azure-devops[Set up authentication] article from Azure Devops official guide to connect to feed.

IMPORTANT: Ignore the settings.xml part as it is created by the script. Only pom.xml modification is needed.

== Appendix

=== Consume library from the main project

In Azure Artifacts, browse to the artifact that you want to install and copy the contents of the <dependency> element and paste it inside the <dependencies> element of your pom.xml file.

Then, go to link:https://docs.microsoft.com/en-us/azure/devops/artifacts/maven/pom-and-settings?view=azure-devops[Set up authentication] article from Azure Devops official guide to connect to feed.

IMPORTANT: Ignore the settings.xml part as is not necessary to consume an artifact.






