= Setting up a Build Pipeline on Azure DevOps

In this section we will create a build pipeline for compiling project code. The script located at `\scripts\pipelines\azure-devops\build_pipeline_generator.sh` will automatically create a build pipeline based on a yml template.

== Prerequisites

This script will copy the corrsponding yml template into your local repository and push into Azure DevOps, so it is necessary that you have in your local repository all the changes done in your Azure DevOps repository. In order to have all the changes execute `git pull` inside your local repository.

== The script

=== Syntax
```
   build_pipeline_generator.sh
        [-n <String>]
        [-l <String>]
        [-d <String>] 
```

=== Arguments
```
    -n    [Required] Name that will be set to the build pipeline.
    -l    [Required] Language or framework of the project.
    -d    [Required] Local directory of your project (the path should be using '/' and not '\'). 
```

=== Examples

Executing the script: +

```
    ./build_pipeline_generator.sh -n <pipeline name> -l <language or framework> -d <project local path>
```

Case study:  +

I have a quarkus project in C:/Users/<my_user>/Desktop/quarkus-project and in my Azure DevOps repository, and I want to generate a build pipeline in order to build my project.

```
    ./build_pipeline_generator.sh -n 'quarkus-project-build' -l 'quarkus' -d C:/Users/<my_user>/Desktop/quarkus-project
```
WARNING: Remember to write the path to the local repository with '/' and not '\'.
