:toc: macro
toc::[]
:idprefix:
:idseparator: -

== Setup Pipeline to provision AWS EKS using Terraform
In this section we will create a pipeline to provision AWS EKS cluster using Terraform scripts. This pipeline will be configured to be triggered every time there is a commit to the Azure DevOps repository, regardless of which branch it is made on.

The creation of the pipeline will follow the project workflow, so a new branch named `feature/provision-aws-eks-pipeline` will be created and the YAML file for the pipeline will be pushed to it. 

Then, a Pull Request (PR) will be created in order to merge the new branch into the appropriate branch (provided in `-b` flag). The PR will be automatically merged if the repository policies are met. If the merge is not possible, either the PR URL will be shown as output, or it will be opened in your web browser if using `-w` flag.

The script located at `/scripts/pipelines/azure-devops/provision_aws_eks.sh` will automatically create this new branch, create a build pipeline based on a YAML template appropriate for the project programming language or framework, create the Pull Request and, if it is possible, merge this new branch into the specified branch.

=== Prerequisites
* Create a service connection in Azure DevOps https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#create-a-service-connection[here]. Make sure the service connection name to be `AWS-Terraform-Connection`. If you need a specific connection name, please modify the same `script_config.cfg`.
* Create AWS S3 Bucket https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-overview.html[here] -  Bucket name and the path is needed to be passed as parameter to the script while executing.
* https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/iam-permissions.md[AWS IAM User has EKS access]
* https://kubernetes.io/docs/tasks/tools/[Install kubectl]


=== Usage

Download the files from `...scripts/terrafom/aws/eks`. 

Run the following command on your command prompt.
```
provision-aws-ek.sh
  -c <configuration file path> \
  -n <name> \
  -d <directory of local project> \
  -b <branch name to which PR will target> \
  -e <AWS EKS clustername> \
  -s <AWS S3 bucket name> \
  
```

=== Flags

```
-n    [Required] Name that will be set to the pipeline.
-d    [Required] Local directory of your project (the path should always be using '/' and not '\').
-c    [Required] Configuration file path.
-e    [Required] AWS EKS Cluster name
-s    [Required] AWS S3 Bucket Name(used by Terraform to store remote state).
-k    [Required] AWS S3 Bucket path(used by Terraform to store remote state file)
-b    [Required] Name of the branch to which the pull request will target. PR is not created if the flag is not provided.
-w               Open the pull request on the web browser if it can not be automatically merged. Requires -b flag.

```

=== Terraform Variables
Open terraform.tfvars and edit or add the needed parameters.
==== VPC
This script will by default create a new VPC with name `k8s-vpc`. However, if you wish to provision AWS EKS in your existing `VPC` please edit `existing_vpc_id` and `existing_vpc_private_subnets` with respective values.

To interact with your cluster, run this command in your terminal:
```
aws eks --region <<region_name>> update-kubeconfig --name <<cluster_name>>
```
