= Setting up a Test Pipeline on Azure DevOps

In this section we will create a Azure DevOps Test pipeline for testing project test cases.

== *Prerequisites:*
Before executing the script be sure your local repository is up to date, pull latest changes with `git pull`.

== *Creating Azure DevOps Test Pipeline using provided script*

The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically create a test pipeline based on a YAML template at `templates/test/test-pipeline.yml`. Configuration file `test-pipeline-config.cfg` can be passed as a mandatory parameter containing all the variables. Other required parameters needs to be passed for the script to execute. 

[loweralpha]
. The script creates a git branch with name `feature/test-pipeline` and `.pipeline` YAML files will be pushed to it.
. Pull Request will be created in order to merge the new branch into the appropriate branch using -b flag. Ex. to the master branch. 
. The PR will be automatically merged if the repository policies are met. If the merge is not possible, PR URL will be shown as output or it will be opened in your web browser if -w flag has been passed.

:hardbreaks-option:
*Note*: If any test pipeline failed, check the logs for the specific pipeline summary. In more actions you can download complete logs which include additional diagnostic information or you can store application logs in user specifed path.

== Usage

```
./pipeline_generator.sh -c <config file path> -n <pipeline name> -l <language or framework> -d <project local path>  -b <target branch> [-w]
```
== Flags

```
-c    [Required] Configuration file for parameter containing all the variables.
-n    [Required] Name that will be set to the quality pipeline."
-d    [Required] Local directory of your project (the path should always be using '/' and not '\')."
-l               Language or framework of the directory. Only required when generating Test pipelines."
-b               Name of the branch to which the Pull Request will target. PR won't create without flag."
-w               Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag."
```
=== Example

==== Quarkus project

```
./pipeline_generator.sh -n quarkus_project_test -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project -c test-pipeline-config.cfg -b master -w
``` 


 






