= Setting up a Build Pipeline on Azure DevOps

In this section we will create a build pipeline for compiling project code. This pipeline will be configured in order to be triggered every time there is a commit to the Azure DevOps repository, regardless of which branch it is made on.

The creation of the pipeline will follow the project workflow, so a new branch named `feature/build-pipeline` will be created and the YAML file for the pipeline will be pushed to it.

The script located at `/scripts/pipelines/azure-devops/build_pipeline_generator.sh` will automatically create a build pipeline based on a YAML template appropiate for the project programming language or framework.

== Prerequisites

This script will commit and push the corresponding YAML template into your repository, so please be sure your local repository is up-to-date (i.e you have pulled latest changes with `git pull`).

== The script

=== Flags
```
    -n    [Required] Name that will be set to the build pipeline.
    -l    [Required] Language or framework of the project.
    -d    [Required] Local directory of your project (the path should always be using '/' and not '\'). 
```

=== Usage

```
    ./build_pipeline_generator.sh -n <pipeline name> -l <language or framework> -d <project local path>
```

=== Examples

==== Quarkus project

```
    ./build_pipeline_generator.sh -n quarkus-project-build -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project
```
CAUTION: Remember to write the path to the local repository with '/' and not '\' on Windows.
