= Setting up a Test Pipeline on Azure DevOps

In this section we will create a Test pipeline on Azure DevOps for running project test cases. This pipeline will be configured in order to be triggered every time a commit to the Azure DevOps repository is done, regardless of which branch it is made on.

The creation of this pipeline will follow the project workflow, so a new branch named `feature/test-pipeline` will be created and the YAML file for the pipeline will be pushed to it.

Then, a Pull Request (PR) will be created in order to merge the new branch into the appropriate branch (provided in `-b` flag). The PR will be automatically merged if the repository policies are met. If the merge is not possible, either the PR URL will be shown as output, or it will be opened in your web browser if using `-w` flag.

The script located at `/scripts/pipelines/azure-devops/pipeline_generator.sh` will automatically create new branch, create a test pipeline based on a YAML template appropriate for the project programming language or framework, create the Pull Request, and if it is possible, merge this new branch into the specified branch.

== Prerequisites

* This script will commit and push the corresponding YAML template into your repository, so please be sure your local repository is up-to-date (i.e you have pulled latest changes with `git pull`).

* [Optional] Having some knowledge about the application, in particular knowing if, when tested, it produces a log file or some other blob (e.g. performance profiling data) interesting to be kept as an artifact.

== Creating the pipeline using provided script

=== Usage
```
pipeline_generator.sh \
  -c <config file path> \
  -n <pipeline name> \
  -l <language or framework> \
  -d <project local path> \
  [-a <artifact source path>] \
  [-b <branch>] \
  [-w]
```

NOTE:  The config file for the test pipeline is located at `/scripts/pipelines/azure-devops/templates/test/test-config.cfg`.

NOTE: If the test pipeline failed, check the logs for the failed test case(s) summary. In _More actions_ (three dots button) you can download complete logs which include additional diagnostic information. Also, you can retrieve the "additional pipeline output" artifact containing the application logs stored in the path specified in `-a` flag (if applicable).

=== Flags
```
-c    [Required] Configuration file containing pipeline definition.
-n    [Required] Name that will be set to the pipeline.
-l    [Required] Language or framework of the project.
-d    [Required] Local directory of your project (the path should always be using '/' and not '\').
-a               Path to be persisted as an artifact after pipeline execution, e.g. where the application stores logs or any other blob on runtime.
-b               Name of the branch to which the Pull Request will target. PR is not created if the flag is not provided.
-w               Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.
```

=== Examples

==== Quarkus project

```
./pipeline_generator.sh -c ./templates/test/test-config.cfg -n quarkus-project-test -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project -b develop -w
```

CAUTION: Remember to write the path to the local repository with '/' and not '\' on Windows.
