
= Setting up a SonarQube instance in AWS

The scope of this section is to deploy an AWS EC2 instance running SonarQube. A script has been created in order to assist you in the launching of a SonarQube instance with an embedded database.

== Getting Started
=== Prerequisites
* https://learn.hashicorp.com/tutorials/terraform/install-cli?in=terraform/aws-get-started[Install Terraform].

* https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[Install AWS CLI].

== Relevant files

* `main.tf` contains declarative definition written in HCL of AWS infrastructure.
* `setup_sonarqube.sh` script to be run on EC2 instance that installs and deploys a container running SonarQube.
* `variables.tf` contains variable definition for `main.tf`.
* `terraform.tfvars` contains values (user-changeable) for the variables defined in `variables.tf`.
* `addparameter.sh` add values to the terraform.tfvars.
* `execute.sh` create the AWS EC2 instance with a Docker container which run SonarQube. 

== Usage

Download the files from `...scripts/terrafom/aws/sonarqube`. Open the file `terraform.tfvars` and edit the needed parameters. +
For inserting new parameters you can also use `addparameter.sh` followed by a parameter name and value *"--Value_name=Parameter"* like in the example below. +

*EXAMPLE:*
```
addparameter.sh --var1=par1 --var2=par2 ...
```
This script will write the new custom parameters to the `terraform.tfvars` file.  

IMPORTANT: If you do not want to change the parameters, you will need a Keypair with the name `sonarqube`.

Run the following script on your command prompt to deploy SonarQube Instance. 

```
execute.sh
```
According to this, it will create an EC2 instance with Ubuntu in AWS and deploy a Docker container with a SonarQube image on it.  On the command line, you will see the IP address of the EC2 instance.

Once the deployment has finished type `+http://localhost:9000+`(replace localhost with the EC2 instance IP-Address from the output on the command prompt) in your browser and you will have access to your SonarQube. The default login values are:

CAUTION: username:   *admin* +
 password:   *admin*