= Upload File as secret in the secret manager of Google Cloud

In this section we will import a file as a secret in the secret manager that will be downloaded in the pipelines that we need.

To upload this file we will need to create a branch called `feature/add-secret-file` to create/update a configuration file containing the information about the secrets to download in the pipelines.

Then we will merge this branch in the appropriate branch (provided in `-b` flag).

== Prerequisites

This script will commit and push the corresponding shell script and configuration file into your repository, so please be sure your local repository is up-to-date (i.e you have pulled latest changes with `git pull`).

=== Usage

```
add-secret-file.sh \
  -d <local directory> \
  -f <local file path> \
  -r <remote file path> \
  -b <target branch> \
  [-n <secret name>] \
  [-p <pipelines list>]
```

=== Flags
```
-d, --local-directory       [Required] Local directory of your project."
-f, --local-file-path       [Required] Local path of the file you want to upload."
-r, --remote-file-path      [Required] Path where the secret will be downloaded inside the pipeline (with the file name)."
-b, --target-branch         [Required] Name of the branch to which the merge will target."
-n, --secret-name                      Name of the secret as it will appear in the secret manager. if not set, we use the name of the file given with '-f'."
-p, --pipelines                        List of the pipelines the secret needs to be downloaded. if not set, it will be downloaded for every pipeline.
```
;
NOTE: the name given with the `-n` has to be compliant with the regex [a-zA-Z0-9_]. (if flag not set and file name given with `-f` is not compliant with the regex, it will be modified to be compliant with it)

=== Examples

add-secret-file.sh -r .pipelines/config/secretboth.txt -d /depots/test-quarkus/ -f /depots/my_true_hangar/setup/Dockerfile -n secretBoth2 -b master -p "test-quarkus,build-quarkus"
