= Setting up a Test Workflow on Github Actions

In this section we will create a test workflow on Github Actions for running project test cases. This workflow will be configured in order to be triggered every time the build workflow is executed successfully on a commit, and consumes the artifact produced by the build workflow.

The creation of this workflow will follow the project workflow, so a new branch named `feature/test-pipeline` will be created and the YAML file for the workflow will be pushed to it.

Then, a Pull Request (PR) will be created in order to merge the new branch into the appropriate branch (provided in `-b` flag). The PR will be automatically merged if the repository policies are met. If the merge is not possible, either the PR URL will be shown as output, or it will be opened in your web browser if using `-w` flag.

The script located at `/scripts/pipelines/github/pipeline_generator.sh` will automatically create this new branch, create a test workflow based on a YAML template appropriate for the project programming language or framework, create the Pull Request, and if it is possible, merge this new branch into the specified branch.

== Prerequisites

* This script will commit and push the corresponding YAML template into your repository, so please be sure your local repository is up-to-date (i.e you have pulled latest changes with `git pull`).

* [Optional] Having some knowledge about the application, in particular knowing if, when tested, it produces a log file or some other blob (e.g. performance profiling data) interesting to be kept as an artifact.

== Creating the pipeline using provided script

=== Usage
```
pipeline_generator.sh \
  -c <config file path> \
  -n <pipeline name> \
  -l <language or framework> \
  -d <project local path> \
  --build-pipeline-name <build pipeline name> \
  [-a <artifact source path>] \
  [-b <branch>] \
  [-w]
```

NOTE:  The config file for the test workflow is located at `/scripts/pipelines/azure-devops/templates/test/test-pipeline.cfg`.

=== Flags
```
-c, --config-file           [Required] Configuration file containing workflow definition.
-n, --pipeline-name         [Required] Name that will be set to the workflow.
-l, --language              [Required] Language or framework of the project.
-d, --local-directory       [Required] Local directory of your project.
    --build-pipeline-name   [Required] Build pipeline name.
-a, --artifact-path                    Path to be persisted as an artifact after workflow execution, e.g. where the application stores logs or any other blob on runtime.
-b, --target-branch                    Name of the branch to which the Pull Request will target. PR is not created if the flag is not provided.
-w                                     Open the Pull Request on the web browser if it cannot be automatically merged. Requires -b flag.
```

=== Examples

==== Quarkus project

```
./pipeline_generator.sh -c ./templates/test/test-pipeline.cfg -n quarkus-project-test -l quarkus -d C:/Users/$USERNAME/Desktop/quarkus-project --build-pipeline-name quarkus-project-build -b develop -w
```

==== Node.js project

```
./pipeline_generator.sh -c ./templates/test/test-pipeline.cfg -n node-project-test -l node -d C:/Users/$USERNAME/Desktop/node-project --build-pipeline-name node-project-build -b develop -w
```
