= Setting up a Package Workflow on Github Actions

In this section we will create a package workflow to build and push a container image of the project application into the specified conatiner registry. This pipeline will be configured in order to be triggered every time the quality pipeline is executed successfully on a commit for `release/*` and `develop` branches, requiring minimal launch for other branches but still enforcing that the quality pipeline has passed . It consumes the artifact produced by the build pipeline.

The creation of this workflow will follow the project workflow, so a new branch named `feature/test-pipeline` will be created and the YAML file for the workflow will be pushed to it.

Then, a Pull Request (PR) will be created in order to merge the new branch into the appropiate branch (provided in `-b`flag). The PR will be automatically merged if the repository policies are met. If the merge is not possible, either the PR URL will be shown as output, or it will be opened in your web browser if using `-w` flag.

The script located at `/scripts/pipelines/github/pipeline_generator.sh` will automatically create this new branch, create a package workflow based on a YAML template appropiate for the project programming language or framework, create the Pull Request, and if it is possible, merge this new branch into the specified branch.

== Prerequisites

* This script will commit and push the corresponding YAML template into your repository, so please be sure your local repository is up-to-date (i.e you have pulled the latest changes with `git pull`).

== Creating the pipeline using provided script

=== Usage
```
pipeline_generator.sh \
  -c <config file path>
  -n <pipeline name> \
  -l <language or framework> \
  -d <project local path> \
  --quality-pipeline-name <quality pipeline name> \
  -i <image name> \
  [-u <registry user>] \
  [-p <registry password>] \
  [--aws-access-key <aws access key>] \
  [--aws-secret-access-key <aws secret access key>] \
  [--aws-region <aws region>] \
  [-b <branch>] \
  [-w]

```

NOTE: The config file for the package workflow is located at `/scripts/pipelines/github/templates/package/package-pipeline.cfg`.

