name: takeoff_cli
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  args: ^2.3.1 
  logging: ^1.1.0
  takeoff_lib:
    path: '../lib'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
