= Appendix - Container Registry
== What is a Container Registry?
* Docker registry is a service that is storing our docker images.
* Docker registry could be hosted by a third party, as public or private registry.
* Could be used one of the below:
  1. Docker Hub (https://docs.docker.com/docker-hub/repos/[link])
  2. Amazon Elastic Container Registry (https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html[ECR])
  3. Google Container Registry (https://cloud.google.com/container-registry/docs/pushing-and-pulling[GCR])
  4. Azure Container Registry (https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-docker-cli?tabs=azure-cli[ACR])
  5. IBM Cloud Container Registry (https://www.ibm.com/cloud/container-registry[link])
  6. Oracle Container Registry (https://docs.oracle.com/en-us/iaas/Content/Registry/Tasks/registrypushingimagesusingthedockercli.htm[link])
  7. Alibaba Cloud Container Registry (https://www.alibabacloud.com/help/doc-detail/198212.htm[link])
  8. GitLab Container Registry (https://docs.gitlab.com/ee/user/packages/container_registry/[link])
  9. JFrog Container Registry (https://jfrog.com/container-registry/[link])
  10. Red Hat Quay  (https://quay.io/[link])
  11. Harbor  (https://goharbor.io/docs/2.3.0/install-config/[link])
  12. Portus  (http://port.us.org/docs/first-steps.html[link])
* We can host the Docker Registry by ourself using "docker registry" or other options like Quay, Harbor, Portus, etc.

== What is a Container Repository?
* Docker repository is a collection of different docker images with same name, that have different tags. 
* Tag is alphanumeric identifier of the image within a repository.
* For example see https://hub.docker.com/r/library/python/tags/[DockerTagExample]. 
  - There are many different tags for the official python image, these tags are all members of the official python repository on the Docker Hub. 
  - Docker Hub is a Docker Registry hosted by Docker.
  
== What is Docker Registry and why to use it?
* The Registry is a stateless, highly scalable server side application that stores and lets you distribute Docker images. 
* The Registry is open-source, under the permissive Apache license.
* You should use the Registry if you want to:
  - tightly control where your images are being stored
  - fully own your images distribution pipeline
  - integrate image storage and distribution tightly into your in-house development workflow
* Users looking for a zero maintenance, ready-to-go solution are encouraged to head-over to the Docker Hub.
* Docker Hub provides a free-to-use, hosted Registry, plus additional features (organization accounts, automated builds, and more).
* The Registry is compatible with Docker engine version 1.6.0 or higher.

== Docker Pull/Push Commands
* Here are some optional commands which we would follow in any of our projects.

1. To pull the hello-world container to our local (or server from where we run this command), use *docker pull*.
2. After making the necessary code changes, we need to tag the container using *docker tag* command (before pushing it to the regitry).
3. After tagging the container, use *docker push* command to push the code changes to the registry.

[source,shell]
----
   docker pull HOSTNAME/PROJECT-ID/IMAGE
   docker tag SOURCE_IMAGE HOSTNAME/PROJECT-ID/IMAGE
   docker push HOSTNAME/PROJECT-ID/IMAGE
----

* The above commands are pretty much same for any container image repo / registries like DockerHub, AWS ECR, ACR, GCR, GHCR and so on. Those are given below for reference.
* Only the logging-in commands may be different for different image repo.

== Azure Container Registry
[source,shell]
----
   az acr login --name mycontainerregistry
   
   docker pull mcr.microsoft.com/hello-world
   docker tag mcr.microsoft.com/hello-world mycontainerregistry.azurecr.io/hello-world:v1.1.2
   docker push mycontainerregistry.azurecr.io/hello-world:v1.1.2
----

== Google Container Registry
[source,shell]
----
   gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://HOSTNAME
   
   docker pull gcr.io/google-samples/hello-app:1.0
   docker tag gcr.io/google-samples/hello-app:1.0 gcr.io/PROJECT_ID/quickstart-image:tag1
   docker push gcr.io/PROJECT_ID/quickstart-image:tag1
----

== GitHub Container Registry
[source,shell]
----
   docker login ghcr.io -u USERNAME --password-stdin
   
   docker pull ghcr.io/OWNER/IMAGE_NAME:1.14.1
   docker tag ghcr.io/OWNER/IMAGE_NAME:1.14.1 ghcr.io/OWNER/IMAGE_NAME:tag1
   docker push ghcr.io/OWNER/IMAGE_NAME:latest
----
