== Activate and prepare Azure DevOps


:url-az-devops: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#choose-your-sign-up-option

:url-az-project:  https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#create-a-project

:url-az-CLI:  https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest

:url-az-board: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/plan-track-work?view=azure-devops&tabs=agile-process


*Prerequisites:*

... Sign up into {url-az-devops}[Azure DevOps] in order to follow the steps of this guide.
... Install the Azure {url-az-CLI}[CLI].

Here we will create an Azure DevOps Project.

1. Create an Azure DevOps project, There are two ways to create an Azure DevOps project:

..  Create an Azure DevOps project manually with the web interface following Microsoft's official {url-az-project}[guide].  
.. Create an Azure DevOps project using an automated script, you can find this script in `/scripts/account-setup/account_create.sh`. 

2. Plan and track your work by creating items in {url-az-board}[Azure Boards], You can follow these instructions when you want to accomplish the following tasks for best process.


== *Setup Azure DevOps using Script*

This script will enable you to create a new project or configure an existing one. Follow the instructions below for more details.

== Syntax

```
   account_create.sh
        [-p <String>]
        [-d <String>]
        [-o <String>]
        [-v <String>]
        [-t <String>]

```
== Arguments

```
    -p    [Required] Name of the new project.
    -d    [Required] Description for the new project.
    -o    [Required] Name of the organization  for which the project will be configured.
    -v    [Required] Visibility accepted values: private or public.
    -t    [Required] PAT token to login Azure DevOps.

```
== *Example:*
I want to create an my_project in `organization-org` organization. Edit all the parameters as desired to create an Azure DevOps project.

Execute the script: 


`bash account_create.sh -p 'my_project' -d 'This_is_an_sample_project' -o 'organization-org' -v 'public' -t 'xxxxxxxxxxxxxx'`

   






