== Activate and prepare Azure DevOps


:url-az-devops: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#choose-your-sign-up-option

:url-az-project:  https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#create-a-project

:url-az-CLI:  https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest

:url-az-board: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/plan-track-work?view=azure-devops&tabs=agile-process


*Prerequisites:*

... You need to be Sign up for an {url-az-devops}[Azure Devops] in order to follow the steps of this guide.
... Install the Azure CLI.

Here we will create an Azure DevOps Project.

1. Create an Azure DevOps project, There are two ways to create an Azure DevOps project:

..  Create an Azure DevOps project manually with the web interface following Microsoft's official {url-az-project}[guide].  
.. Create an Azure DevOps project using an automated script, you can find this script in `/scripts/account-setup/account_create.sh`. 

3. Plan and track your work by creating items in {url-az-board}[Azure Boards], You can follow these instructions when you want to accomplish the followingtasks for best process.


== *Setup Azure DevOps using Script*

This script will enable you to create a new project or configure an existing one. Follow the instructions below for more details.

== Syntax

```
   account_create.sh
        [-p <String>]
        [-d <String>]
        [-o <String>]
        [-v <String>]
        [-t <String>]

```
== Arguments

```
    -p    [Required] Name of the new project.
    -d    [Required] Description for the new project.
    -o    [Required] Name of the organization  for which the project will be configured.
    -v    [Required] Visibility accepted values: private or public.
    -t    [Required] PAT token to login Azure DevOps.

```

== *Script Usage*

Execute the script to create new project from scratch 
 


1.  Edit all the parameters as desired to create an Azure DevOps project.

== *Example:*
I want to create an devon4java project in `devon-hangar` organization.

`bash account_create.sh -p 'devon4java' -d 'devon4java_Application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`

   






