== Activate and prepare Azure DevOps


:url-az-devops: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#choose-your-sign-up-option

:url-az-project:  https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#create-a-project

:url-az-CLI:  https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest

:url-az-board: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/plan-track-work?view=azure-devops&tabs=agile-process

:url-pat-token: https://docs.searchunify.com/Content/Content-Sources/Azure-Generate-Personal-Access-Token.htm

== *Prerequisites:*

. Sign up into {url-az-devops}[Azure DevOps].
. Install the Azure {url-az-CLI}[CLI].
. Create a  {url-pat-token}[Personal Access Token (PAT)] in Azure DevOps.

== *Creating the Azure DevOps project*

The scope of this section is to prepare and activate an Azure DevOps account.

There  are two ways to create an Azure DevOps project:

.  Create an Azure DevOps project manually with the web interface following Microsoft's official {url-az-project}[guide].  

. Create an Azure DevOps project using an automated script, you can find this script in `/scripts/account-setup/account_create.sh`. 

Additionally you are able to plan and track your work by creating items in {url-az-board}[Azure Boards], you can follow these instructions when you want to accomplish the following tasks for best practices.


== *Setup Azure DevOps using Script*

This script will enable you to create a new project or configure an existing one. Follow the instructions below for more details.

== Syntax

```
   account_create.sh
        [-p <String>]
        [-d <String>]
        [-o <String>]
        [-v <String>]
        [-t <String>]

```
== Flags

```
    -p    [Required] Name of the new project.
    -d    [Required] Description for the new project.
    -o    [Required] Name of the organization  for which the project will be configured.
    -v    [Required] Visibility accepted values: private or public.
    -t    [Required] PAT token to login Azure DevOps.

```

== Usage

`bash account_create.sh -p 'my_project' -d 'This_is_a_sample_project' -o 'organization-org' -v 'public' -t 'xxxxxxxxxxxxxx'`

== Examples


=== Quarkus project

I want to create a devon4quarkus project with the description 'This is a quarkus application' in an organization called `devon-hangar`.

`bash account-create.sh -p 'devon4quarkus' -d 'This is a quarkus application' -o 'devon-hangar' -v 'public' -t 'xxxxxxxxxxxxxx'`


note: testing
   






