== Activate and prepare Azure DevOps


:url-az-devops: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#choose-your-sign-up-option

:url-az-project:  https://docs.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#create-a-project

:url-az-CLI:  https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest

:url-az-board: https://docs.microsoft.com/en-us/azure/devops/boards/get-started/plan-track-work?view=azure-devops&tabs=agile-process

:url-pat-token: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#create-a-pat

:url-script-url: https://github.com/prathibhapadma/hangar/blob/Feature/block-1/Scripts/account-setup/project_create.sh

== *Prerequisites:*

. Sign up into {url-az-devops}[Azure DevOps].
. Install the Azure {url-az-CLI}[CLI].
. Create an Azure Devops {url-pat-token}[Personal Access Token (PAT)] by following Microsoft official guide.

== *Creating the Azure DevOps project*

The scope of this section is to prepare and activate an Azure DevOps account.

There  are two ways to create an Azure DevOps project:

.  Create an Azure DevOps project manually with the web interface following Microsoft's official {url-az-project}[guide].  

. Create an Azure DevOps project using an automated script, you can find this script in {url-script-url}[`/scripts/account-setup/project_create.sh`]. 

Additionally you are able to plan and track your work by creating items in {url-az-board}[Azure Boards], you can follow these instruction when you want to accomplish the following task for best practices.


== *Setup Azure DevOps using Script*

This script will enable you to create a new project or configure an existing one. Follow the instruction below for more details.

== Syntax

```
   project_create.sh
        [-p <String>]
	[-o <String>]
        [-d <String>]
        [-v <String>]
        [-t <String>]

```
== Flags

```
    -p    [Required] Name of the new project.
    -d    [Required] Description for the new project.
    -o    [Required] Name of the organization  for which the project will be configured.
    -v    [Required] Visibility accepted values: private or public.
    -t    [Required] PAT token to login Azure DevOps.

```

== Usage

```
bash project_create.sh \
	-p 'my_project' \
	-o 'organization-org' \
	-d 'This_is_a_sample_project' \
	-v 'public' \
	-t 'xxxxxxxxxxxxxx'
```

== Examples


=== Quarkus project

create a devon4quarkus project with the description 'This is a quarkus application' in an organization called `devon-hangar`.

`bash project_create.sh -p 'devon4quarkus' -o 'devon-hangar' -d 'This is a quarkus application' -v 'public' -t 'xxxxxxxxxxxxxx'`

   






