== Activate and prepare Azure DevOps 

:url-az-CLI:  https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest

:url-az-devops-account: https://azure.microsoft.com/en-in/services/devops/

*Prerequisites:*

1. Install the {url-az-CLI}[Azure CLI.]
2. Create Azure {url-az-devops-account}[DevOps] Account.

== *Setup Azure DevOps  using Azure CLI*

Automated the Azure Devops setup using script, you can find Script in this folder `/Scripts/account-setup/account_create.sh`.

1. Install the Azure DevOps Extension to manage Azure DevOps Services from the command line .
2. Create Personal Access Tokens (PAT) to authorization header to access REST APIs. and Set Secret values under `pat_token.txt`.

3. Login to Azure Devops `az devops login` by using PAT token.

4. Configure the organization and project by using script. 

*Script Execute:*

1. Create `pat_token.txt` for storing sensitive data (PAT Token).
2. Edit *account_create.sh* file to change the organization name `Organization={{Organization-org}}` and project name `project={{project}}`.
3. Execute the script `./account_create.sh`
4. Check your logs for Configured list.




