= Appendix - Container Registry

This section contains additional content about container registries, container repositories and managing container images. 

== What is a Container Registry?^[1]^^[2]^
* Docker registry is a service that stores our docker images.
* A container registry could be hosted by a third party or self-hosted, as public or private registry.

* Managed - We can use any of the below mentioned container registry that are managed by the provider.
  1. Docker Hub (https://docs.docker.com/docker-hub/repos/[link])
  2. Amazon Elastic Container Registry (https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html[ECR])
  3. Google Container Registry (https://cloud.google.com/container-registry/docs/pushing-and-pulling[GCR])
  4. Azure Container Registry (https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-docker-cli?tabs=azure-cli[ACR])
  5. IBM Cloud Container Registry (https://www.ibm.com/cloud/container-registry[link])
  6. Oracle Container Registry (https://docs.oracle.com/en-us/iaas/Content/Registry/Tasks/registrypushingimagesusingthedockercli.htm[link])
  7. Alibaba Cloud Container Registry (https://www.alibabacloud.com/help/doc-detail/198212.htm[link])
  8. GitLab Container Registry (https://docs.gitlab.com/ee/user/packages/container_registry/[link])
 * Hosted - We can host the Docker Registry by ourself using "docker registry" or any of the below options.
  9. JFrog Container Registry (https://jfrog.com/container-registry/[link])
  10. Red Hat Quay  (https://quay.io/[link])
  11. Harbor  (https://goharbor.io/docs/2.3.0/install-config/[link])
  12. Portus  (http://port.us.org/docs/first-steps.html[link])

== What is a Container Repository?^[2]^
* Docker repository is a collection of different docker images with same name, that have different tags. 
* Tag is alphanumeric identifier of the image within a repository.
* For example see https://hub.docker.com/r/library/python/tags/[python image tags at Docker Hub]. 
  - There are many different tags for the official python image, these tags are all part of the official python repository on Docker Hub. 
  - Docker Hub is a container registry hosted by _Docker, Inc_.
  
== What is Docker Registry and why to use it?^[1]^
* The Registry is a stateless, highly scalable server side application that stores and lets you distribute Docker images. 
* The Registry is open-source, under the permissive Apache license.
* You should use the Registry if you want to:
  - tightly control where your images are being stored
  - fully own your images distribution pipeline
  - integrate image storage and distribution tightly into your in-house development workflow
* Users looking for a zero maintenance, ready-to-go solution are encouraged to head-over to the Docker Hub.
* Docker Hub provides a free-to-use, hosted Registry, plus additional features (organization accounts, automated builds, and more).
* The Registry is compatible with Docker engine version 1.6.0 or higher.

== Docker Pull/Push Commands^[1]^
* Here are some optional commands which we would follow in any of our projects.

1. To pull the hello-world container to our local (or server from where we run this command), use *docker pull*.
2. After making the necessary code changes, we need to tag the container using *docker tag* command (before pushing it to the regitry).
3. After tagging the container, use *docker push* command to push the code changes to the registry.

[source,shell]
----
   docker pull <hostname>/<project-id>/<imagename>
   docker tag <source-imagename> <hostname>/<project-id>/<imagename>:<tag>
   docker push <hostname>/<project-id>/<imagename>
----

* The above commands are pretty much same for any container image repo / registries like DockerHub, AWS ECR, ACR, GCR, GHCR and so on. Those are given below for reference.
* Only the logging-in commands may be different for different image repo.

== Azure Container Registry^[3]^
* https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-portal[ACR] is a private registry service from Azure Cloud.
* Azure CLI commands start with "az" which is shown below for login.
* Registry can be created using the following command.

[source,shell]
----
   az acr create --resource-group <resourcegroup-name> --name <registry-name> --sku Basic
----

Output is similar to the following:
[source,json]
----
{
  "adminUserEnabled": false,
  "creationDate": "2019-01-08T22:32:13.175925+00:00",
  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/myContainerRegistry007",
  "location": "eastus",
  "loginServer": "mycontainerregistry007.azurecr.io",
  "name": "myContainerRegistry007",
  "provisioningState": "Succeeded",
  "resourceGroup": "myResourceGroup",
  "sku": {
    "name": "Basic",
    "tier": "Basic"
  },
  "status": null,
  "storageAccount": null,
  "tags": {},
  "type": "Microsoft.ContainerRegistry/registries"
}
----

* Docker commands can be used for pulling, tagging and pushing container images as shown below.

[source,shell]
----
   az acr login --name <registry-name>
   
   docker pull mcr.microsoft.com/hello-world
   docker tag mcr.microsoft.com/hello-world mycontainerregistry.azurecr.io/hello-world:v1.1.2
   docker push mycontainerregistry.azurecr.io/hello-world:v1.1.2
----

== Google Container Registry^[4]^
* https://cloud.google.com/container-registry/docs/overview[GCR] is a private registry service from Google Cloud.
* Google Cloud CLI commands start with "gcr" which is shown below for login
* Docker commands can be used for pulling, tagging and pushing container images as shown below

[source,shell]
----
   gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://HOSTNAME
   
   docker pull gcr.io/google-samples/hello-app:1.0
   docker tag gcr.io/google-samples/hello-app:1.0 gcr.io/PROJECT_ID/quickstart-image:tag1
   docker push gcr.io/PROJECT_ID/quickstart-image:tag1
----

== GitHub Container Registry^[5]^
* https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry[GHCR] is a private registry service from GitHub.
* Docker commands can be used for logging into registry and for pulling, tagging, pushing container images as shown below

[source,shell]
----
   docker login ghcr.io -u USERNAME --password-stdin
   
   docker pull ghcr.io/OWNER/IMAGE_NAME:1.14.1
   docker tag ghcr.io/OWNER/IMAGE_NAME:1.14.1 ghcr.io/OWNER/IMAGE_NAME:tag1
   docker push ghcr.io/OWNER/IMAGE_NAME:latest
----

== References
* 1. ^Docker (https://docs.docker.com/registry/)
* 2. ^StackOverflow (https://stackoverflow.com/questions/34004076/)
* 3. ^Azure (https://docs.microsoft.com/en-us/azure/container-registry)
* 4. ^Google Cloud
* 5. ^GitHub
