= Appendix - Container Registry

This section contains additional content about container registries, container repositories and managing container images. 

== What is a Container Registry?^[1]^^[2]^
* Container registry is a service that stores our container images.
* A container registry could be hosted by a third party or self-hosted, as public or private registry.

** Managed. Hosted and provided as a service by a provider, most of the times a cloud vendor.
  *** https://docs.docker.com/docker-hub/repos/[Docker Hub]
  *** https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html[Amazon Elastic Container Registry (ECR)]
  *** https://cloud.google.com/container-registry/docs/pushing-and-pulling[Google Container Registry (GCR)]
  *** https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-docker-cli?tabs=azure-cli[Azure Container Registry (ACR)]
  *** https://www.ibm.com/cloud/container-registry[IBM Cloud Container Registry]
  *** https://docs.oracle.com/en-us/iaas/Content/Registry/Tasks/registrypushingimagesusingthedockercli.htm[Oracle Container Registry]
  *** https://www.alibabacloud.com/help/doc-detail/198212.htm[Alibaba Cloud Container Registry]
  *** https://docs.gitlab.com/ee/user/packages/container_registry/[GitLab Container Registry]
  *** https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry[GitHub Container Registry]
 ** Hosted. We can host a container registry on our own. Proprietary (commercial) and open source solutions are available.
  *** Official https://docs.docker.com/registry/[Docker Registry]
  *** https://jfrog.com/container-registry/[JFrog Container Registry]
  *** https://quay.io/[Red Hat Quay]
  *** https://goharbor.io/docs/2.3.0/install-config/[Harbor]
  *** http://port.us.org/docs/first-steps.html[Portus]

== What is a Container Repository?^[2]^
* Container repository is a collection of different container images with same name, that have different tags. 
* Tag is alphanumeric identifier of the image within a repository.
* For example see https://hub.docker.com/r/library/python/tags/[python image tags at Docker Hub]. 
  - There are many different tags for the official python image, these tags are all part of the official python repository on Docker Hub. 
  - Docker Hub is a container registry hosted by _Docker, Inc_.

== Docker Pull/Push Commands^[1]^
* Here are some optional commands which we would follow in any of our projects.

1. To pull the hello-world container to our local (or server from where we run this command), use *docker pull*.
2. After making the necessary code changes, we need to tag the container using *docker tag* command (before pushing it to the regitry).
3. After tagging the container, use *docker push* command to push the code changes to the registry.

[source,shell]
----
   docker pull <hostname>/<project-id>/<imagename>
   docker tag <source-imagename> <hostname>/<project-id>/<imagename>:<tag>
   docker push <hostname>/<project-id>/<imagename>
----

* The above commands are pretty much same for any container image repo / registries like DockerHub, AWS ECR, ACR, GCR, GHCR and so on. Those are given below for reference.
* Only the logging-in commands may be different for different image repo.

== Google Container Registry^[4]^
* https://cloud.google.com/container-registry/docs/overview[GCR] is a private registry service from Google Cloud.
* Google Cloud CLI commands start with "gcr" which is shown below for login
* Docker commands can be used for pulling, tagging and pushing container images as shown below

[source,shell]
----
   gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://HOSTNAME
   
   docker pull gcr.io/google-samples/hello-app:1.0
   docker tag gcr.io/google-samples/hello-app:1.0 gcr.io/PROJECT_ID/quickstart-image:tag1
   docker push gcr.io/PROJECT_ID/quickstart-image:tag1
----

== GitHub Container Registry^[5]^
* https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry[GHCR] is a private registry service from GitHub.
* Docker commands can be used for logging into registry and for pulling, tagging, pushing container images as shown below

[source,shell]
----
   docker login ghcr.io -u USERNAME --password-stdin
   
   docker pull ghcr.io/OWNER/IMAGE_NAME:1.14.1
   docker tag ghcr.io/OWNER/IMAGE_NAME:1.14.1 ghcr.io/OWNER/IMAGE_NAME:tag1
   docker push ghcr.io/OWNER/IMAGE_NAME:latest
----

== References
* 1. ^Docker (https://docs.docker.com/registry/)
* 2. ^StackOverflow (https://stackoverflow.com/questions/34004076/)
* 3. ^Azure (https://docs.microsoft.com/en-us/azure/container-registry)
* 4. ^Google Cloud (https://cloud.google.com/container-registry/docs/pushing-and-pulling)
* 5. ^GitHub (https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
