:toc: macro
toc::[]
:idprefix:
:idseparator: -

== How to use Docker Hub?
* We will demonstrate how to pull an image from Docker Hub to your local machine, and then push a version with a tag back to your own repository.
* Step#1 - You will need a Docker Hub account. If you dont have one, please create one here - https://hub.docker.com/
* Step#2 - Once you have a Docker Hub account, you can create a repository in just a few clicks at https://hub.docker.com/repositories. First, click "Create Repository"
* Step#3 - Use the following command and login to Docker Hub account. You will see a message saying "Login Succeeded" after authenticating with Password.
  - `sudo docker login -u <username>`
  - Ex: `sudo docker login -u sundharakanthan`
* Step#4 - Use the following command to pull the docker container image from Docker Hub to local machine.
  - `sudo docker pull hello-world`
  - Ex: `sudo docker pull sundharakanthan/nodejssampleprj`
* Step#5 - Use the following command to push an image to private repository.
  - `sudo docker push <username>/<imagename>`
  - Ex: 
[source,ruby]
----
	sudo docker images
	sudo docker tag nodejssampleprj sundharakanthan/nodejssampleprj:v1.1.1.1
	sudo docker images
	sudo docker pull sundharakanthan/nodejssampleprj:v1.1.1.1
----
* Going back to our Docker Hub account, we can see the new tag is stored in our private repository [https://hub.docker.com/u/sundharakanthan].

== Docker Pull/Push Commands 
[source,ruby]
----
docker pull HOSTNAME/PROJECT-ID/IMAGE
docker tag SOURCE_IMAGE HOSTNAME/PROJECT-ID/IMAGE
docker push HOSTNAME/PROJECT-ID/IMAGE
----
== AWS Elastic Container Registry
[source,ruby]
----
aws ecr get-login-password \
    --region region | docker login \
    --username AWS \
    --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com
----
* To create a repository

The following create-repository example creates a repository inside the specified namespace in the default registry for an account.

[source,ruby]
----
aws ecr create-repository \ 
    --repository-name project-a/nginx-web-app \ 
    --region us-west-2
----
* Output:
[source,ruby]
----
{
    "repository": { 
        "registryId": "123456789012",
        "repositoryName": "sample-repo",
        "repositoryArn": "arn:aws:ecr:us-west-2:123456789012:repository/project-a/nginx-web-app"
    }
}
----

* `docker pull aws_account_id.dkr.ecr.region.amazonaws.com/hello-world:latest`
* `docker tag hello-world:latest aws_account_id.dkr.ecr.region.amazonaws.com/hello-world:latest`
* `docker push aws_account_id.dkr.ecr.region.amazonaws.com/hello-world:latest`
