:toc: macro
toc::[]
:idprefix:
:idseparator: -

== Setup Container Repository
In this section, we will see how to create/access Container Registry to pull/tag/push container images.

* A container image is a lightweight, standalone, executable package of software that includes everything needed to run an application - code, runtime, system tools, system libraries and settings.^[1]^
* A container registry is a repository, or collection of repositories, used to store container images for Kubernetes, DevOps, and container-based application development.^[2]^

== Prerequisites
* Docker Hub account is required to access Docker Hub Registry.
* AWS account and AWS CLI installation are required to access AWS Container Registry.
* Azure account and Azure CLI installation are required to access Azure Container Registry.

== How to use Docker Hub?
Docker Hub is a container registry/repository which is used to save container images.^[1]^ We will also demonstrate how to pull a container image from Docker Hub to your local machine, and then push a version with a tag back to your own repository.

* You will need a Docker Hub account. If you do not have one, please create one https://hub.docker.com/[here]. 
* Once you have a Docker Hub account, you can create a repository in just a few clicks in the https://hub.docker.com/repositories[link here]. First, click "Create Repository".
* Use the following command and login to Docker Hub account. You will see a message saying "Login Succeeded" after authenticating with Password.
[source,shell]
----
   docker login -u <username>
----
* Use the following command to pull the container image from Docker Hub to local machine.
* Pull the desired container images to our local repository with `docker pull` command.
[source,shell]
----
   docker pull <hostname>/<project-id>/<imagename>
----
* After making the necessary changes, tag the container image using the `docker tag` command.
* After tagging our container image, use `docker push` command to push the changes into the Docker Hub.
[source,shell]
----   
   docker tag <source-image> <hostname>/<project-id>/<image>
----
* Use the following command to push a container image to private repository.
[source,shell]
----
   docker push <hostname>/<project-id>/<imagename>
----
* Going back to our Docker Hub account, we can see the new tag stored in our private repository.
* Docker hub has no registry reference (<hostname>) since it is default whereas AWS, Azure, GCP, etc will have references like ecr.io, azr.io, gcr.io, etc.

== AWS Elastic Container Registry
* First, login to AWS ECR registry^[3]^ with the following command:

[source,shell]
----
   aws ecr get-login-password \
       --region <region> | docker login \
       --username AWS \
       --password-stdin <aws-account-id>.dkr.ecr.<region>.amazonaws.com
----
* `<region>` represents AWS Region which is a separate geographic area and the examples are us-east-1, eu-west-1, ap-south-1. 

* Create a repository inside the specified namespace in the default registry for an account like in the example below:

[source,shell]
----
   aws ecr create-repository \ 
       --repository-name project-a/nginx-web-app \ 
       --region us-east-1
----

*Output:*
[source,json]
----
   {
       "repository": { 
           "registryId": "123456789012",
           "repositoryName": "sample-repo",
           "repositoryArn": "arn:aws:ecr:us-east-1:123456789012:repository/project-a/nginx-web-app"
       }
   }
----

=== Pulling and Pushing images

Here are some optional commands which we would follow in any of our container projects.

* To pull the hello-world container to our local (or server from where we run this command), use this.
[source,shell]
----
    docker pull <aws-account-id>.dkr.ecr.<region>.amazonaws.com/hello-world:latest
----
* After making the necessary code changes, we need to tag the container using this command (before pushing it to the regitry).
[source,shell]
----
    docker tag hello-world:latest <aws-account-id>.dkr.ecr.<region>.amazonaws.com/hello-world:latest
----
* After tagging the container image, use this command to push the changes to the repository.
[source,shell]
----
    docker push <aws-account-id>.dkr.ecr.<region>.amazonaws.com/hello-world:latest
----

== Azure Container Registry^[4]^
* https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-portal[ACR] is a private registry service from Azure Cloud.
* Azure CLI commands start with "az" which is shown below for login.
* Registry can be created using the following command.

[source,shell]
----
   az acr create --resource-group <resourcegroup-name> --name <registry-name> --sku Basic
----

Output is similar to the following:
[source,json]
----
{
  "adminUserEnabled": false,
  "creationDate": "2019-01-08T22:32:13.175925+00:00",
  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/myContainerRegistry007",
  "location": "eastus",
  "loginServer": "mycontainerregistry007.azurecr.io",
  "name": "myContainerRegistry007",
  "provisioningState": "Succeeded",
  "resourceGroup": "myResourceGroup",
  "sku": {
    "name": "Basic",
    "tier": "Basic"
  },
  "status": null,
  "storageAccount": null,
  "tags": {},
  "type": "Microsoft.ContainerRegistry/registries"
}
----

* Docker commands can be used for pulling, tagging and pushing container images as shown below.

[source,shell]
----
   az acr login --name <registry-name>
   
   docker pull mcr.microsoft.com/hello-world
   docker tag mcr.microsoft.com/hello-world mycontainerregistry.azurecr.io/hello-world:v1.1.2
   docker push mycontainerregistry.azurecr.io/hello-world:v1.1.2
----

=== References
* 1 - ^Docker (https://docs.docker.com/docker-hub/)
* 2 - ^RedHat (https://www.redhat.com/en/topics/cloud-native-apps/what-is-a-container-registry)
* 3 - ^AWS (https://docs.aws.amazon.com/ecr/)
* 4 - ^Azure (https://docs.microsoft.com/en-us/azure/container-registry/)
