:toc: macro
toc::[]
:idprefix:
:idseparator: -
= Prepare AWS account for deployment with Azure DevOps
The scope of this section is to prepare an AWS account to be ready for deployment from Azure DevOps to AWS EKS. By the end of this guide, a new user with the required permissions will be created.

== Preparing environment
First of all, https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[install AWS CLI for your OS]. 



In case you do not have permission to create new IAM users, request it to your AWS administrator asking for the following policies attached. Then go to <<configure-cli>>.
```
AmazonEKSClusterPolicy
AmazonEKSWorkerNodePolicy
AmazonEKSServicePolicy
AmazonEKS_CNI_Policy
AmazonEKSVPCResourceController
```

== Using the script to create the user

The script located at `/scripts/accounts/aws/create-user.sh` will automatically create a user, also enrolling it in a newly created group with the required policies attached.

In case you do not have an AWS access key (needed to authenticate through API), follow https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey[this guide] to create it.

=== Flags
```
-u      [Required] Username for the new user
-g      [Required] Group name for the group to be created or used
-p      [Optional] Policies to be attached to the group, splitted by comma
-f      [Optional] Path to a file containing the policies to be attached to the group
-a      [Optional] AWS administrator access key
-s      [Optional] AWS administrator secret key
-r      [Optional] AWS region
```

=== Example
```
./create-user.sh -u "Bob" -g "DevOps" -f "./policies.txt" -a "<accessKeyAWS>" -s "<secretKeyAWS>" -r "eu-west-1" 
```

=== After execution
On success, the newly created user access data will be shown as output:
```
Access key ID: <accessKeyID>
Secret access key: <secretAccessKey>
```
IMPORTANT: It is mandatory to store the access key ID and the secret access key securely at this point, as *the will not be retrievable again*.

== Configure AWS CLI [[configure-cli]]
Once you have been provided with an IAM user, setup the AWS CLI using the following command:
```
aws configure
```
Fill the prompted fields with your data:
```
AWS Access Key ID [None]: <accessKeyID>
AWS Secret Access Key [None]: <secretAccessKey>
Default region name [None]: eu-west-1
Default output format [None]: json
```
Now you have AWS CLI ready to use.
